import os

from ._profile_types import BrowserChannel


def _get_enable_default_extensions_default() -> bool:
	"""Get the default value for enable_default_extensions from env var or True."""
	env_val = os.getenv('AGENTYC_DISABLE_EXTENSIONS')
	if env_val is not None:
		return env_val.lower() in ('0', 'false', 'no', 'off', '')
	return True


CHROME_DEBUG_PORT = 9242
DOMAIN_OPTIMIZATION_THRESHOLD = 100

CHROME_DISABLED_COMPONENTS = [
	'AcceptCHFrame',
	'AutoExpandDetailsElement',
	'AvoidUnnecessaryBeforeUnloadCheckSync',
	'CertificateTransparencyComponentUpdater',
	'DestroyProfileOnBrowserClose',
	'DialMediaRouteProvider',
	'ExtensionManifestV2Disabled',
	'GlobalMediaControls',
	'HttpsUpgrades',
	'ImprovedCookieControls',
	'LazyFrameLoading',
	'LensOverlay',
	'MediaRouter',
	'PaintHolding',
	'ThirdPartyStoragePartitioning',
	'Translate',
	'AutomationControlled',
	'BackForwardCache',
	'OptimizationHints',
	'ProcessPerSiteUpToMainFrameThreshold',
	'InterestFeedContentSuggestions',
	'CalculateNativeWinOcclusion',
	'HeavyAdPrivacyMitigations',
	'PrivacySandboxSettings4',
	'AutofillServerCommunication',
	'CrashReporting',
	'OverscrollHistoryNavigation',
	'InfiniteSessionRestore',
	'ExtensionDisableUnsupportedDeveloper',
	'ExtensionManifestV2Unsupported',
]

CHROME_HEADLESS_ARGS = [
	'--headless=new',
]

CHROME_DOCKER_ARGS = [
	'--no-sandbox',
	'--disable-gpu-sandbox',
	'--disable-setuid-sandbox',
	'--disable-dev-shm-usage',
	'--no-xshm',
	'--no-zygote',
	'--disable-site-isolation-trials',
]

CHROME_DISABLE_SECURITY_ARGS = [
	'--disable-site-isolation-trials',
	'--disable-web-security',
	'--disable-features=IsolateOrigins,site-per-process',
	'--allow-running-insecure-content',
	'--ignore-certificate-errors',
	'--ignore-ssl-errors',
	'--ignore-certificate-errors-spki-list',
]

CHROME_DETERMINISTIC_RENDERING_ARGS = [
	'--deterministic-mode',
	'--js-flags=--random-seed=1157259159',
	'--force-device-scale-factor=2',
	'--enable-webgl',
	'--font-render-hinting=none',
	'--force-color-profile=srgb',
]

CHROME_DEFAULT_ARGS = [
	'--disable-field-trial-config',
	'--disable-background-networking',
	'--disable-background-timer-throttling',
	'--disable-backgrounding-occluded-windows',
	'--disable-back-forward-cache',
	'--disable-breakpad',
	'--disable-client-side-phishing-detection',
	'--disable-component-update',
	'--no-default-browser-check',
	'--disable-dev-shm-usage',
	'--disable-hang-monitor',
	'--disable-ipc-flooding-protection',
	'--disable-popup-blocking',
	'--disable-prompt-on-repost',
	'--disable-renderer-backgrounding',
	'--metrics-recording-only',
	'--no-first-run',
	'--no-service-autorun',
	'--export-tagged-pdf',
	'--disable-search-engine-choice-screen',
	'--unsafely-disable-devtools-self-xss-warnings',
	'--enable-features=NetworkService,NetworkServiceInProcess',
	'--enable-network-information-downlink-max',
	'--disable-sync',
	'--allow-legacy-extension-manifests',
	'--allow-pre-commit-input',
	'--disable-blink-features=AutomationControlled',
	'--install-autogenerated-theme=0,0,0',
	'--log-level=2',
	'--disable-focus-on-load',
	'--disable-window-activation',
	'--generate-pdf-document-outline',
	'--no-pings',
	'--ash-no-nudges',
	'--disable-infobars',
	'--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
	'--hide-crash-restore-bubble',
	'--suppress-message-center-popups',
	'--disable-domain-reliability',
	'--disable-datasaver-prompt',
	'--disable-speech-synthesis-api',
	'--disable-speech-api',
	'--disable-print-preview',
	'--safebrowsing-disable-auto-update',
	'--disable-external-intent-requests',
	'--disable-desktop-notifications',
	'--noerrdialogs',
	'--silent-debugger-extension-api',
	'--disable-extensions-http-throttling',
	'--extensions-on-chrome-urls',
	'--disable-default-apps',
	f'--disable-features={",".join(CHROME_DISABLED_COMPONENTS)}',
]

AGENTYC_DEFAULT_CHANNEL = BrowserChannel.CHROMIUM
