#!/usr/bin/env python3
"""Run the test-only MV3 P0-T2 probe.

Offline mode is the default and performs only deterministic fixture checks.
`--headed` requires `--launch-chrome` for live inspection; without it the
script fails closed rather than attaching to an existing debug endpoint.
`--require-live` makes that isolated live inspection required and fails when
Chrome is unavailable. `--launch-chrome` is an explicit opt-in; it creates a
short-lived system-temporary profile unless an explicit disposable temporary
profile is supplied.
The script never touches the default Chrome profile.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import ipaddress
import json
import math
import os
import re
import shutil
import signal
import socket
import struct
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from pathlib import Path
from typing import Any

from artifact_envelope import envelope as add_envelope
from artifact_envelope import write_json_atomic

ROOT = Path(__file__).resolve().parents[1]
EXTENSION_DIR = ROOT / "extension" / "probes"
DEFAULT_ARTIFACT_DIR = ROOT / "artifacts" / "p0-extension"
REQUIRED_PERMISSIONS = {"debugger", "nativeMessaging", "storage", "tabGroups", "tabs"}
EXPECTED_EXTENSION_NAME = "agentyc Phase 0 Probe"
EXPECTED_SERVICE_WORKER = "service_worker.js"
EXTENSION_ID_PATTERN = re.compile(r"^[a-p]{32}$")
WEBSOCKET_HEADER_LIMIT = 16 * 1024
WEBSOCKET_FRAME_LIMIT = 64 * 1024
RESULT_HANDOFF_LIMIT = 16 * 1024
WORKER_DISCOVERY_TIMEOUT = 8.0
WORKER_DISCOVERY_INTERVAL = 0.1
WEBSOCKET_GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
_LAST_CLEANUP_OK = True


def _contains_control(value: str) -> bool:
    return any(ord(character) < 0x20 or ord(character) == 0x7F for character in value)


def load_manifest() -> dict[str, Any]:
    manifest = json.loads((EXTENSION_DIR / "manifest.json").read_text(encoding="utf-8"))
    if manifest.get("manifest_version") != 3:
        raise ValueError("probe manifest is not MV3")
    if manifest.get("name") != EXPECTED_EXTENSION_NAME:
        raise ValueError("probe manifest is not the expected extension")
    background = manifest.get("background")
    if not isinstance(background, dict) or background.get("service_worker") != EXPECTED_SERVICE_WORKER:
        raise ValueError("probe manifest does not name the expected service worker")
    permissions = set(manifest.get("permissions", []))
    missing = REQUIRED_PERMISSIONS - permissions
    if missing:
        raise ValueError(f"probe manifest is missing permissions: {sorted(missing)}")
    for filename in ("service_worker.js", "probe.html", "probe.js", "fixture.html"):
        if not (EXTENSION_DIR / filename).is_file():
            raise ValueError(f"probe fixture is missing {filename}")
    return manifest


def safe_artifact_dir(value: str) -> Path:
    requested = Path(value)
    if not requested.is_absolute():
        requested = ROOT / requested
    current = requested
    while current != current.parent:
        if current.is_symlink():
            raise SystemExit("artifact path components must not be symlinks")
        current = current.parent
    requested = requested.resolve()
    allowed = DEFAULT_ARTIFACT_DIR.resolve()
    if requested != allowed and allowed not in requested.parents:
        raise SystemExit("artifact directory must be inside artifacts/p0-extension/")
    return requested


def safe_profile_dir(value: str) -> Path:
    requested = Path(value).expanduser()
    if not requested.is_absolute():
        raise SystemExit("profile directory must be an absolute disposable temporary path")
    current = requested
    while current != current.parent:
        if current.is_symlink():
            raise SystemExit("profile path components must not be symlinks")
        current = current.parent
    requested = requested.resolve(strict=False)
    temporary_root = Path(tempfile.gettempdir()).resolve()
    if requested == temporary_root or temporary_root not in requested.parents:
        raise SystemExit("profile directory must be inside the system temporary directory")
    if requested.exists() and (not requested.is_dir() or any(requested.iterdir())):
        raise SystemExit("profile directory must be absent or empty disposable temporary storage")
    return requested


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


_NO_REDIRECT_OPENER = urllib.request.build_opener(_NoRedirect)


def chrome_endpoint(port: int, path: str) -> Any:
    request = urllib.request.Request(f"http://127.0.0.1:{port}{path}")
    with _NO_REDIRECT_OPENER.open(request, timeout=0.75) as response:
        return json.loads(response.read().decode("utf-8"))


def new_request_id() -> str:
    """Return a per-run UUID generated by the operating system CSPRNG."""
    return str(uuid.uuid4())


class DevToolsSocket:
    """Minimal bounded RFC 6455 WebSocket client for local Chrome CDP."""

    def __init__(self, url: str, timeout: float = 2.0) -> None:
        if timeout <= 0:
            raise ValueError("debugger websocket timeout must be positive")
        try:
            parsed = urllib.parse.urlparse(url)
            hostname = parsed.hostname
            port = parsed.port
        except (TypeError, ValueError) as error:
            raise ValueError("debugger websocket URL is invalid") from error
        if (
            parsed.scheme != "ws"
            or hostname not in {"127.0.0.1", "localhost"}
            or port is None
            or parsed.username is not None
            or parsed.password is not None
            or parsed.fragment
            or not parsed.path.startswith("/")
            or _contains_control(parsed.path)
            or _contains_control(parsed.query)
            or not 1 <= port <= 65535
        ):
            raise ValueError("debugger websocket must be a local ws URL without credentials or fragments")
        try:
            resolved_hosts = {
                sockaddr[-1][0]
                for sockaddr in socket.getaddrinfo(hostname, port, type=socket.SOCK_STREAM)
            }
        except OSError as error:
            raise ValueError("debugger websocket hostname could not be resolved") from error
        if not resolved_hosts or any(not ipaddress.ip_address(host).is_loopback for host in resolved_hosts):
            raise ValueError("debugger websocket hostname is not loopback")

        self.socket: socket.socket | None = None
        self.timeout = timeout
        self._receive_buffer = bytearray()
        self.next_id = 0
        key = base64.b64encode(os.urandom(16)).decode("ascii")
        request_target = parsed.path or "/"
        if parsed.query:
            request_target += f"?{parsed.query}"
        request = (
            f"GET {request_target} HTTP/1.1\r\n"
            f"Host: {hostname}:{port}\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            f"Sec-WebSocket-Key: {key}\r\n"
            "Sec-WebSocket-Version: 13\r\n"
            "\r\n"
        ).encode("ascii")

        raw_socket = socket.create_connection((hostname, port), timeout=timeout)
        self.socket = raw_socket
        try:
            raw_socket.settimeout(timeout)
            raw_socket.sendall(request)
            response = self._read_http_headers()
            self._validate_handshake(response, key)
        except (OSError, ValueError, TypeError, UnicodeError, struct.error):
            self.close()
            raise

    def _read_http_headers(self) -> bytes:
        if self.socket is None:
            raise OSError("debugger websocket is closed")
        data = bytearray()
        while True:
            end = data.find(b"\r\n\r\n")
            if end >= 0:
                header_end = end + 4
                self._receive_buffer.extend(data[header_end:])
                return bytes(data[:header_end])
            if len(data) >= WEBSOCKET_HEADER_LIMIT:
                raise ValueError("debugger websocket headers exceed the bound")
            chunk = self.socket.recv(min(4096, WEBSOCKET_HEADER_LIMIT - len(data)))
            if not chunk:
                raise OSError("debugger websocket closed during handshake")
            data.extend(chunk)

    def _validate_handshake(self, response: bytes, key: str) -> None:
        try:
            text = response.decode("ascii")
        except UnicodeDecodeError as error:
            raise ValueError("debugger websocket handshake was not ASCII") from error
        if not text.endswith("\r\n\r\n"):
            raise ValueError("debugger websocket handshake was not terminated")
        lines = text[:-2].split("\r\n")
        if not lines or lines[-1] != "":
            raise ValueError("debugger websocket handshake was not terminated")
        status = lines[0].split(" ", 2)
        if (
            len(status) != 3
            or status[0] != "HTTP/1.1"
            or status[1] != "101"
            or _contains_control(status[2])
        ):
            raise OSError("debugger websocket handshake failed")

        headers: dict[str, str] = {}
        for line in lines[1:-1]:
            if not line or line[0] in " \t" or ":" not in line:
                raise ValueError("debugger websocket response contained an invalid header")
            name, value = line.split(":", 1)
            if not name or not re.fullmatch(r"[!#$%&'*+.^_`|~0-9A-Za-z-]+", name):
                raise ValueError("debugger websocket response contained an invalid header name")
            if _contains_control(value):
                raise ValueError("debugger websocket response contained a control character")
            key_name = name.lower()
            if key_name in headers:
                raise ValueError("debugger websocket response repeated a header")
            headers[key_name] = value.strip(" \t")

        if headers.get("upgrade", "").lower() != "websocket":
            raise ValueError("debugger websocket response omitted Upgrade: websocket")
        connection_tokens = {
            token.strip().lower() for token in headers.get("connection", "").split(",") if token.strip()
        }
        if "upgrade" not in connection_tokens:
            raise ValueError("debugger websocket response omitted Connection: Upgrade")
        accept = headers.get("sec-websocket-accept")
        if accept is None:
            raise ValueError("debugger websocket response omitted Sec-WebSocket-Accept")
        expected_accept = base64.b64encode(hashlib.sha1((key + WEBSOCKET_GUID).encode("ascii")).digest()).decode("ascii")
        if not hmac.compare_digest(accept, expected_accept):
            raise ValueError("debugger websocket accept key did not match the request")
        if "sec-websocket-extensions" in headers:
            raise ValueError("debugger websocket negotiated an unsupported extension")
        if "sec-websocket-protocol" in headers:
            raise ValueError("debugger websocket negotiated an unrequested subprotocol")

    def _frame(self, payload: bytes, opcode: int = 1) -> bytes:
        if not isinstance(payload, (bytes, bytearray, memoryview)):
            raise TypeError("debugger websocket payload must be bytes-like")
        payload = bytes(payload)
        if opcode not in {0, 1, 2, 8, 9, 10}:
            raise ValueError("debugger websocket opcode is invalid")
        if opcode >= 8 and len(payload) > 125:
            raise ValueError("debugger websocket control frame exceeds the bound")
        if len(payload) > WEBSOCKET_FRAME_LIMIT:
            raise ValueError("debugger message exceeds the probe bound")
        mask = os.urandom(4)
        length = len(payload)
        if length < 126:
            header = bytes([0x80 | opcode, 0x80 | length])
        elif length <= 0xFFFF:
            header = bytes([0x80 | opcode, 0x80 | 126]) + struct.pack("!H", length)
        else:
            header = bytes([0x80 | opcode, 0x80 | 127]) + struct.pack("!Q", length)
        masked = bytes(byte ^ mask[index % 4] for index, byte in enumerate(payload))
        return header + mask + masked

    def _receive_frame(self) -> tuple[bool, int, bytes]:
        header = self._receive_exact(2)
        first, second = header
        fin = bool(first & 0x80)
        if first & 0x70:
            raise ValueError("debugger websocket used a reserved frame bit")
        opcode = first & 0x0F
        if opcode not in {0, 1, 2, 8, 9, 10}:
            raise ValueError("debugger websocket opcode is invalid")
        if second & 0x80:
            raise ValueError("debugger websocket server frame was masked")
        length_code = second & 0x7F
        if length_code < 126:
            length = length_code
        elif length_code == 126:
            length = struct.unpack("!H", self._receive_exact(2))[0]
            if length < 126:
                raise ValueError("debugger websocket used a non-minimal frame length")
        else:
            length = struct.unpack("!Q", self._receive_exact(8))[0]
            if length & (1 << 63):
                raise ValueError("debugger websocket frame length is invalid")
            if length < 65536:
                raise ValueError("debugger websocket used a non-minimal frame length")
        if length > WEBSOCKET_FRAME_LIMIT:
            raise ValueError("debugger frame exceeds the probe bound")
        if opcode >= 8 and (not fin or length > 125):
            raise ValueError("debugger websocket control frame is invalid")
        payload = self._receive_exact(length)
        if opcode == 8:
            self._validate_close_payload(payload)
        return fin, opcode, payload

    def _validate_close_payload(self, payload: bytes) -> None:
        if len(payload) == 1:
            raise ValueError("debugger websocket close frame has an invalid payload")
        if len(payload) < 2:
            return
        code = struct.unpack("!H", payload[:2])[0]
        valid_code = (
            (1000 <= code <= 1003)
            or (1007 <= code <= 1014)
            or (3000 <= code <= 4999)
        )
        if not valid_code:
            raise ValueError("debugger websocket close code is invalid")
        try:
            payload[2:].decode("utf-8")
        except UnicodeDecodeError as error:
            raise ValueError("debugger websocket close reason is invalid UTF-8") from error

    def _receive(self) -> tuple[int, bytes]:
        """Receive one complete, unfragmented frame for compatibility with old callers."""
        fin, opcode, payload = self._receive_frame()
        if not fin or opcode == 0:
            raise ValueError("fragmented debugger websocket messages require the message reader")
        return opcode, payload

    def _receive_message(self) -> bytes:
        fragments = bytearray()
        message_opcode: int | None = None
        while True:
            fin, opcode, payload = self._receive_frame()
            if opcode == 9:
                if self.socket is None:
                    raise OSError("debugger websocket is closed")
                self.socket.sendall(self._frame(payload, opcode=10))
                continue
            if opcode == 10:
                continue
            if opcode == 8:
                try:
                    if self.socket is not None:
                        self.socket.sendall(self._frame(payload, opcode=8))
                except OSError:
                    pass
                raise OSError("debugger websocket closed")
            if opcode == 0:
                if message_opcode is None:
                    raise ValueError("debugger websocket continuation arrived without a message")
            elif opcode in {1, 2}:
                if message_opcode is not None:
                    raise ValueError("debugger websocket started a message before finishing the prior one")
                message_opcode = opcode
            else:
                raise ValueError("debugger websocket data opcode is invalid")
            if len(fragments) + len(payload) > WEBSOCKET_FRAME_LIMIT:
                raise ValueError("debugger websocket fragmented message exceeds the bound")
            fragments.extend(payload)
            if fin:
                if message_opcode != 1:
                    raise ValueError("debugger websocket returned a non-text CDP message")
                return bytes(fragments)

    def _receive_exact(self, size: int) -> bytes:
        if size < 0:
            raise ValueError("debugger websocket read size is invalid")
        result = bytearray()
        while len(result) < size:
            if self._receive_buffer:
                take = min(size - len(result), len(self._receive_buffer))
                result.extend(self._receive_buffer[:take])
                del self._receive_buffer[:take]
                continue
            if self.socket is None:
                raise OSError("debugger websocket is closed")
            chunk = self.socket.recv(min(size - len(result), WEBSOCKET_FRAME_LIMIT))
            if not chunk:
                raise OSError("debugger websocket closed")
            result.extend(chunk)
        return bytes(result)

    def command(self, method: str, params: dict[str, Any] | None = None) -> Any:
        if not isinstance(method, str) or not method or len(method) > 256:
            raise ValueError("debugger command method is invalid")
        if params is not None and not isinstance(params, dict):
            raise TypeError("debugger command parameters must be an object")
        self.next_id += 1
        command_id = self.next_id
        payload = json.dumps(
            {"id": command_id, "method": method, "params": params or {}},
            separators=(",", ":"),
        ).encode("utf-8")
        if len(payload) > WEBSOCKET_FRAME_LIMIT:
            raise ValueError("debugger command exceeds the probe bound")
        if self.socket is None:
            raise OSError("debugger websocket is closed")
        self.socket.sendall(self._frame(payload))
        deadline = time.monotonic() + 3.0
        while time.monotonic() < deadline:
            remaining = deadline - time.monotonic()
            try:
                self.socket.settimeout(min(self.timeout, max(0.01, remaining)))
                frame = self._receive_message()
            except TimeoutError as error:
                raise TimeoutError("debugger command timed out") from error
            try:
                message = json.loads(frame.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError) as error:
                raise ValueError("debugger websocket returned invalid JSON") from error
            if not isinstance(message, dict):
                raise TypeError("debugger websocket returned a non-object message")
            if "id" in message and not isinstance(message["id"], int):
                raise ValueError("debugger websocket returned an invalid command id")
            if message.get("id") == command_id:
                if "error" in message:
                    raise OSError("debugger command rejected")
                return message.get("result")
        raise TimeoutError("debugger command timed out")

    def close(self) -> None:
        sock = self.socket
        self.socket = None
        if sock is None:
            return
        try:
            sock.close()
        except OSError:
            pass


def _runtime_value(result: Any) -> Any:
    if not isinstance(result, dict) or result.get("exceptionDetails") is not None:
        raise ValueError("extension runtime evaluation failed")
    remote = result.get("result")
    if not isinstance(remote, dict) or "value" not in remote:
        raise ValueError("extension runtime evaluation returned no value")
    return remote["value"]


def _worker_candidate(target: Any, expected_port: int | None = None) -> tuple[str, str] | None:
    if not isinstance(target, dict) or target.get("type") != "service_worker":
        return None
    target_url = target.get("url")
    websocket_url = target.get("webSocketDebuggerUrl")
    if not isinstance(target_url, str) or not isinstance(websocket_url, str):
        return None
    try:
        parsed = urllib.parse.urlparse(target_url)
        extension_id = parsed.hostname
        parsed_port = parsed.port
    except ValueError:
        return None
    try:
        websocket = urllib.parse.urlparse(websocket_url)
        websocket_port = websocket.port
    except ValueError:
        return None
    expected_url = f"chrome-extension://{extension_id}/{EXPECTED_SERVICE_WORKER}"
    if (
        parsed.scheme != "chrome-extension"
        or parsed.username is not None
        or parsed.password is not None
        or parsed_port is not None
        or parsed.query
        or parsed.fragment
        or parsed.path != f"/{EXPECTED_SERVICE_WORKER}"
        or not isinstance(extension_id, str)
        or not EXTENSION_ID_PATTERN.fullmatch(extension_id)
        or target_url != expected_url
        or websocket.scheme != "ws"
        or websocket.hostname not in {"127.0.0.1", "localhost"}
        or websocket_port is None
        or expected_port is not None and websocket_port != expected_port
        or websocket.username is not None
        or websocket.password is not None
        or websocket.fragment
    ):
        return None
    return extension_id, websocket_url


def _expected_extension_manifest(manifest: dict[str, Any] | None) -> dict[str, Any]:
    if manifest is not None:
        return manifest
    return {
        "manifest_version": 3,
        "name": EXPECTED_EXTENSION_NAME,
        "version": "0.0.1",
        "permissions": sorted(REQUIRED_PERMISSIONS),
        "background": {"service_worker": EXPECTED_SERVICE_WORKER},
    }


def _is_expected_worker(identity: Any, extension_id: str, manifest: dict[str, Any]) -> bool:
    background = manifest.get("background")
    service_worker = background.get("service_worker") if isinstance(background, dict) else None
    if not isinstance(service_worker, str) or service_worker != EXPECTED_SERVICE_WORKER:
        return False
    return (
        isinstance(identity, dict)
        and identity.get("runtime_id") == extension_id
        and identity.get("manifest_version") == manifest.get("manifest_version")
        and identity.get("name") == manifest.get("name")
        and identity.get("version") == manifest.get("version")
        and identity.get("service_worker") == service_worker
        and identity.get("origin") == f"chrome-extension://{extension_id}"
        and identity.get("pathname") == f"/{service_worker}"
    )


def _cleanup_owned_profile(profile: Path | None) -> None:
    global _LAST_CLEANUP_OK
    if profile is None or not profile.exists():
        return
    try:
        shutil.rmtree(profile)
    except OSError:
        _LAST_CLEANUP_OK = False
    if profile.exists():
        _LAST_CLEANUP_OK = False


def _safe_stop_process(process: subprocess.Popen[bytes]) -> bool:
    global _LAST_CLEANUP_OK
    success = True
    try:
        if process.poll() is None:
            try:
                os.killpg(process.pid, signal.SIGTERM)
            except (OSError, AttributeError):
                try:
                    process.terminate()
                except OSError:
                    success = False
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except (OSError, AttributeError):
                try:
                    process.kill()
                except OSError:
                    success = False
            try:
                process.wait(timeout=5)
            except (OSError, subprocess.TimeoutExpired):
                success = False
    except (OSError, ValueError):
        success = False
    if process.poll() is not None:
        return success
    _LAST_CLEANUP_OK = False
    return False


def extension_probe_result(
    port: int,
    targets: list[dict[str, Any]],
    expected_manifest: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run the probe only after selecting one identity-verified worker."""
    request_id = new_request_id()
    manifest = _expected_extension_manifest(expected_manifest)
    candidates = [_worker_candidate(target, port) for target in targets]
    candidates = [candidate for candidate in candidates if candidate is not None]
    if not candidates:
        return {"status": "live_unavailable", "limitation": "the expected probe service worker was not observed"}

    verified: list[DevToolsSocket] = []
    for extension_id, websocket_url in candidates:
        client: DevToolsSocket | None = None
        try:
            client = DevToolsSocket(websocket_url)
            client.command("Runtime.enable")
            identity_result = client.command(
                "Runtime.evaluate",
                {
                    "expression": "(() => { const manifest = chrome.runtime.getManifest(); return { runtime_id: chrome.runtime.id, manifest_version: manifest.manifest_version, name: manifest.name, version: manifest.version, service_worker: manifest.background?.service_worker ?? null, origin: location.origin, pathname: location.pathname }; })()",
                    "returnByValue": True,
                },
            )
            identity = _runtime_value(identity_result)
            if _is_expected_worker(identity, extension_id, manifest):
                verified.append(client)
                client = None
        except (OSError, ValueError, TypeError, KeyError, AttributeError, IndexError, struct.error):
            pass
        finally:
            if client is not None:
                client.close()

    if len(verified) != 1:
        for client in verified:
            client.close()
        return {
            "status": "live_unavailable",
            "limitation": "the expected probe extension worker was absent or ambiguous",
        }

    socket_client = verified[0]
    try:
        request_literal = json.dumps(request_id)
        fixture_literal = json.dumps((EXTENSION_DIR / "fixture.html").resolve().as_uri())
        trigger = socket_client.command(
            "Runtime.evaluate",
            {
                "expression": f"(async () => {{ await chrome.storage.local.remove('last_probe'); await chrome.storage.local.set({{run_probe: {{request_id: {request_literal}, fixture_url: {fixture_literal}}}}}); return true; }})()",
                "awaitPromise": True,
                "returnByValue": True,
            },
        )
        if _runtime_value(trigger) is not True:
            raise ValueError("extension probe trigger was not acknowledged")
        deadline = time.monotonic() + 8.0
        while time.monotonic() < deadline:
            result = socket_client.command(
                "Runtime.evaluate",
                {
                    "expression": "chrome.storage.local.get('last_probe').then((value) => value.last_probe ?? null)",
                    "awaitPromise": True,
                    "returnByValue": True,
                },
            )
            value = _runtime_value(result)
            if value is None:
                time.sleep(0.1)
                continue
            encoded = json.dumps(value, separators=(",", ":")).encode("utf-8")
            if len(encoded) > RESULT_HANDOFF_LIMIT:
                return {
                    "status": "live_unavailable",
                    "limitation": "extension result handoff exceeded the probe bound",
                }
            if not isinstance(value, dict) or value.get("request_id") != request_id:
                time.sleep(0.1)
                continue
            permissions = value.get("permissions")
            permissions_match = isinstance(permissions, list) and set(permissions) == set(manifest.get("permissions", []))
            transcript = value.get("handshake_transcript")
            transcript_valid = transcript == ["hello_accepted", "probe_accepted"]
            required = {
                "extension_loaded": value.get("extension_loaded") is True,
                "fixture_identity_passed": value.get("fixture_identity_passed") is True,
                "debugger_command_passed": value.get("debugger_command_passed") is True,
                "debugger_event_received": value.get("debugger_event_received") is True,
                "tab_group_created": value.get("tab_group_created") is True,
                "native_messaging_passed": value.get("native_messaging_passed") is True,
                "debugger_cleanup_passed": value.get("debugger_cleanup_passed") is True,
                "cleanup_passed": value.get("cleanup_passed") is True,
                "screenshot_captured": value.get("screenshot_captured") is True,
                "extension_identity_passed": value.get("extension_version") == manifest.get("version") and permissions_match,
            }
            if value.get("ok") is True and all(required.values()) and transcript_valid:
                return {
                    "status": "live_passed",
                    **required,
                    "chrome_mediated_native_messaging": True,
                    "screenshot_captured": True,
                    "screenshots": [{"captured": True, "format": "png"}],
                    "handshake_transcript": transcript,
                }
            return {
                "status": "live_unavailable",
                **required,
                "handshake_transcript": transcript if isinstance(transcript, list) else [],
                "limitation": "extension probe returned incomplete evidence",
            }
        return {
            "status": "live_unavailable",
            "limitation": "extension probe result was not received before the deadline",
        }
    except (OSError, ValueError, TypeError, KeyError, AttributeError, IndexError, TimeoutError, struct.error):
        return {"status": "live_unavailable", "limitation": "extension result handoff failed closed"}
    finally:
        socket_client.close()


def wait_for_chrome(port: int, timeout: float = 8.0) -> dict[str, Any] | None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            value = chrome_endpoint(port, "/json/version")
            return value if isinstance(value, dict) else None
        except (OSError, urllib.error.URLError, ValueError):
            time.sleep(0.1)
    return None


def chrome_binary(value: str | None) -> str | None:
    if value:
        return value
    candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
        "google-chrome",
        "google-chrome-stable",
        "chromium",
        "chromium-browser",
    ]
    for candidate in candidates:
        if os.path.isabs(candidate) and Path(candidate).is_file():
            return candidate
        resolved = shutil.which(candidate)
        if resolved:
            return resolved
    return None


def _endpoint_belongs_to_process(port: int, process: subprocess.Popen[bytes]) -> bool:
    """Verify the launched process group owns the listener before using CDP."""
    lsof = shutil.which("lsof")
    if lsof is None:
        return False
    try:
        result = subprocess.run(
            [lsof, "-nP", f"-iTCP:{port}", "-sTCP:LISTEN", "-Fp"],
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
        listener_pids = {
            int(line[1:])
            for line in result.stdout.splitlines()
            if line.startswith("p") and line[1:].isdigit()
        }
        process_group = os.getpgid(process.pid)
        return any(os.getpgid(pid) == process_group for pid in listener_pids)
    except (OSError, ValueError, subprocess.SubprocessError):
        return False


def wait_for_probe_worker(
    port: int,
    process: subprocess.Popen[bytes],
    timeout: float = WORKER_DISCOVERY_TIMEOUT,
) -> list[dict[str, Any]] | None:
    """Poll the launched process for one exact probe worker, failing closed."""
    if not math.isfinite(timeout) or timeout <= 0:
        raise ValueError("worker discovery timeout must be positive and finite")
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not _endpoint_belongs_to_process(port, process):
            return None
        try:
            targets = chrome_endpoint(port, "/json/list")
        except (OSError, urllib.error.URLError, ValueError):
            targets = None
        if isinstance(targets, list) and any(_worker_candidate(target, port) for target in targets):
            return targets
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        time.sleep(min(WORKER_DISCOVERY_INTERVAL, remaining))
    return None


def inspect_live(
    port: int,
    profile_dir: Path | None,
    launch: bool,
    binary: str | None,
    artifact_dir: Path,
    manifest: dict[str, Any] | None = None,
) -> dict[str, Any]:
    global _LAST_CLEANUP_OK
    _LAST_CLEANUP_OK = True
    del artifact_dir
    if not launch:
        return {
            "status": "live_unavailable",
            "limitation": (
                "existing-endpoint-not-isolated: refusing to attach to an existing "
                "Chrome debug endpoint; pass --launch-chrome to use a disposable "
                "temporary profile."
            ),
        }
    owned_profile: Path | None = profile_dir if launch and profile_dir is not None else None
    if launch:
        try:
            chrome_endpoint(port, "/json/version")
        except (OSError, urllib.error.URLError, ValueError):
            pass
        else:
            _cleanup_owned_profile(owned_profile)
            return {"status": "live_unavailable", "limitation": f"debug port {port} is already in use; refusing to attach or launch ambiguously."}
    process: subprocess.Popen[bytes] | None = None
    launched = False
    try:
        if launch:
            executable = chrome_binary(binary)
            if executable is None:
                return {"status": "live_unavailable", "limitation": "Chrome binary was not found; install Chrome or pass --chrome-binary."}
            if profile_dir is None:
                owned_profile = Path(tempfile.mkdtemp(prefix="agentyc-p0-profile-"))
                profile_dir = owned_profile
            assert profile_dir is not None
            if profile_dir.exists() and any(profile_dir.iterdir()):
                return {"status": "live_unavailable", "limitation": "the supplied disposable Chrome profile is not empty"}
            profile_dir.mkdir(parents=True, exist_ok=True)
            fixture = (EXTENSION_DIR / "fixture.html").resolve().as_uri()
            command = [
                executable,
                f"--user-data-dir={profile_dir}",
                f"--load-extension={EXTENSION_DIR}",
                f"--remote-debugging-port={port}",
                "--no-first-run",
                "--no-default-browser-check",
                "--disable-background-networking",
                "--new-window",
                fixture,
            ]
            process = subprocess.Popen(
                command,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )
            launched = True
        version = wait_for_chrome(port)
        if version is None:
            return {"status": "live_unavailable", "limitation": "Chrome did not expose the requested debug endpoint."}
        if process is None or not _endpoint_belongs_to_process(port, process):
            return {"status": "live_unavailable", "limitation": "the debug endpoint owner could not be bound to the probe-launched Chrome process"}
        targets = wait_for_probe_worker(port, process)
        target_count = len(targets) if isinstance(targets, list) else None
        extension = extension_probe_result(
            port,
            targets if isinstance(targets, list) else [],
            expected_manifest=manifest,
        )
        return {
            "status": extension.get("status", "live_unavailable"),
            "chrome_version": version.get("Browser", "unknown"),
            "target_count": target_count,
            "launched_by_probe": launched,
            "extension_loaded": extension.get("extension_loaded", False),
            "extension_identity_passed": extension.get("extension_identity_passed", False),
            "fixture_identity_passed": extension.get("fixture_identity_passed", False),
            "debugger_command_passed": extension.get("debugger_command_passed", False),
            "debugger_event_received": extension.get("debugger_event_received", False),
            "event_received": extension.get("debugger_event_received", False),
            "tab_group_created": extension.get("tab_group_created", False),
            "native_messaging_passed": extension.get("native_messaging_passed", False),
            "chrome_mediated_native_messaging": extension.get("chrome_mediated_native_messaging", False),
            "debugger_cleanup_passed": extension.get("debugger_cleanup_passed", False),
            "cleanup_passed": extension.get("cleanup_passed", False),
            "screenshot_captured": extension.get("screenshot_captured", False),
            "screenshots": extension.get("screenshots", []),
            "handshake_transcript": extension.get("handshake_transcript", []),
            "permission_prompts": {"status": "not_recorded", "required_manual_review": True},
            "limitation": extension.get("limitation"),
        }
    except (OSError, ValueError, TypeError, KeyError, AttributeError, IndexError, TimeoutError, struct.error, subprocess.SubprocessError):
        return {"status": "live_unavailable", "limitation": "live Chrome inspection failed closed"}
    finally:
        if process is not None and not _safe_stop_process(process):
            _LAST_CLEANUP_OK = False
        _cleanup_owned_profile(owned_profile)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--headed",
        action="store_true",
        help="request isolated live Chrome inspection; requires --launch-chrome",
    )
    parser.add_argument(
        "--require-live",
        "--required-live",
        dest="require_live",
        action="store_true",
        help="require live Chrome inspection and exit nonzero when unavailable",
    )
    parser.add_argument("--launch-chrome", action="store_true", help="explicitly launch isolated Chrome; never implied by default")
    parser.add_argument("--profile-dir", help="optional absolute disposable profile path inside the system temporary directory")
    parser.add_argument("--chrome-binary")
    parser.add_argument("--debug-port", type=int, default=9222)
    parser.add_argument("--artifact-dir", default="artifacts/p0-extension")
    args = parser.parse_args()
    if args.launch_chrome and not args.headed:
        parser.error("--launch-chrome requires --headed")
    if args.require_live and not args.headed:
        parser.error("--require-live requires --headed")
    artifact_dir = safe_artifact_dir(args.artifact_dir)
    profile_dir = safe_profile_dir(args.profile_dir) if args.profile_dir else None
    manifest = load_manifest()
    live_required = bool(args.require_live or args.launch_chrome)
    report: dict[str, Any] = {
        "probe": "P0-T2",
        "status": "offline_passed",
        "manifest_version": manifest["manifest_version"],
        "extension_version": manifest["version"],
        "permissions": manifest["permissions"],
        "mode": "headed" if args.headed else "offline",
        "live": {
            "requested": bool(args.headed),
            "required": live_required,
            "status": "not_requested",
        },
        "safety": {
            "default_chrome_launch": False,
            "default_profile_mutation": False,
            "raw_ids_logged": False,
            "secrets_logged": False,
            "fixture_only_mutation": True,
        },
        "handshake_transcript": [],
        "screenshots": [],
        "limitations": [],
    }
    if args.headed:
        live = inspect_live(args.debug_port, profile_dir, args.launch_chrome, args.chrome_binary, artifact_dir, manifest)
        if not _LAST_CLEANUP_OK:
            live = {"status": "live_unavailable", "limitation": "live probe cleanup failed; process or disposable profile may remain"}
        report["live"] = {"requested": True, "required": live_required, **live}
        report["handshake_transcript"] = live.get("handshake_transcript", [])
        report["screenshots"] = live.get("screenshots", [])
        if live["status"] == "live_passed":
            report["status"] = "live_passed"
        elif live["status"] == "live_unavailable":
            report["status"] = "live_required_unavailable" if live_required else "live_optional_unavailable"
            report["limitations"].append(live["limitation"])
        elif live_required:
            # /json/version proves only that a debugging endpoint is reachable.
            # It does not prove that the MV3 extension, debugger permission,
            # tab-group mutation, and Native Messaging handshake succeeded.
            report["status"] = "live_required_unavailable"
            report["limitations"].append(
                "Chrome endpoint was observed, but the extension probe did not supply complete evidence; "
                "an endpoint alone cannot close the live gate."
            )
        else:
            report["status"] = "live_observed"
            if live.get("limitation"):
                report["limitations"].append(live["limitation"])
    else:
        report["limitations"].append("Real Chrome, extension installation, and Native Messaging registration were not requested.")
    artifact_dir.mkdir(parents=True, exist_ok=True)
    add_envelope(report, kind="chrome-extension-probe")
    output = artifact_dir / "report.json"
    try:
        write_json_atomic(output, report)
    except (OSError, ValueError) as error:
        print(f"chrome probe error: {type(error).__name__}", file=sys.stderr)
        return 2
    print(json.dumps(report, indent=2, sort_keys=True))
    return 1 if report["status"] == "live_required_unavailable" else 0


if __name__ == "__main__":
    raise SystemExit(main())
