// Public TypeScript facade for the logical task-space SDK contracts.
export type {
  ActionOperation,
  ActionOptions,
  ActionReceipt,
  BrowserClient,
  ConnectOptions,
  CreateSpaceOptions,
  EventsOptions,
  LeaseOptions,
  LogicalActionId,
  LogicalPageId,
  LogicalSpaceId,
  ManagedPageOptions,
  OperationCliMapping,
  OperationDefinition,
  Page,
  PageOptions,
  ReclaimOptions,
  RequestOptions,
  SpaceRecord,
  SubmitActionRequest,
  TaskSpace,
  WaitOptions,
} from "./index.d.ts";
