"""CDP-native MCP helpers and tab utilities."""

from __future__ import annotations

from agentyc.mcp.cdp_debug_session_tools import (
	_get_console_logs,
	_get_downloads,
	_get_focused_element,
	_get_network_log,
	_register_cdp_event_listeners,
	_set_viewport,
)
from agentyc.mcp.cdp_interaction_tools import (
	_clear_cookies,
	_double_click,
	_drag_to,
	_get_cookies,
	_get_html,
	_get_viewport_coords,
	_hover,
	_load_state,
	_resolve_element_coords,
	_right_click,
	_save_state,
	_screenshot,
	_scroll_to_text,
	_set_cookies,
	_wait_for_network_idle,
)
from agentyc.mcp.cdp_tabs_trace_tools import (
	_clear_logs,
	_close_tab,
	_get_attribute,
	_handle_dialog,
	_list_tabs,
	_new_tab,
	_start_trace,
	_stop_trace,
	_switch_tab,
	_wait_for_stable_dom,
	_wait_for_tab,
)

__all__ = [
	'_get_html',
	'_screenshot',
	'_get_viewport_coords',
	'_resolve_element_coords',
	'_hover',
	'_double_click',
	'_drag_to',
	'_scroll_to_text',
	'_save_state',
	'_load_state',
	'_wait_for_network_idle',
	'_right_click',
	'_get_cookies',
	'_set_cookies',
	'_clear_cookies',
	'_register_cdp_event_listeners',
	'_get_console_logs',
	'_get_network_log',
	'_get_downloads',
	'_set_viewport',
	'_get_focused_element',
	'_list_tabs',
	'_switch_tab',
	'_wait_for_tab',
	'_new_tab',
	'_close_tab',
	'_wait_for_stable_dom',
	'_handle_dialog',
	'_get_attribute',
	'_clear_logs',
	'_start_trace',
	'_stop_trace',
]
