"""Bound helper methods for AgentycServer."""

from __future__ import annotations

from typing import Any

from agentyc.mcp.action_runtime import (
	_cache_state_payload,
	_classify_action_error,
	_click,
	_ensure_extract_runtime,
	_evaluate,
	_extract_content,
	_find_elements,
	_format_action_error,
	_get_browser_state,
	_get_dropdown_options,
	_go_back,
	_go_forward,
	_inject_extraction_metadata,
	_mark_browser_state_cache_clean,
	_mark_browser_state_cache_dirty,
	_navigate,
	_new_tab_postcondition_satisfied,
	_press_key,
	_refresh,
	_refresh_selector_map,
	_resolve_element_index,
	_resolve_live_element,
	_resolve_upload_available_file_paths,
	_run_tool_action,
	_save_as_pdf,
	_scroll,
	_search_page,
	_select_option,
	_type_text,
	_upload_file,
	_validate_actionable_element,
	_wait,
	_wait_for_element,
)
from agentyc.mcp.cdp_tools import (
	_clear_cookies,
	_clear_logs,
	_close_tab,
	_double_click,
	_drag_to,
	_get_attribute,
	_get_console_logs,
	_get_cookies,
	_get_downloads,
	_get_focused_element,
	_get_html,
	_get_network_log,
	_get_viewport_coords,
	_handle_dialog,
	_hover,
	_list_tabs,
	_load_state,
	_new_tab,
	_register_cdp_event_listeners,
	_resolve_element_coords,
	_right_click,
	_save_state,
	_screenshot,
	_scroll_to_text,
	_set_cookies,
	_set_viewport,
	_start_trace,
	_stop_trace,
	_switch_tab,
	_wait_for_network_idle,
	_wait_for_stable_dom,
)
from agentyc.mcp.debug_tools import _export_debug_bundle, _wait_for_request, _wait_for_response
from agentyc.mcp.intent_tools import _set_intent
from agentyc.mcp.navigation_runtime import (
	_page_contains_visible_text,
	_recover_click_navigation_if_unavailable,
	_wait_for_click_navigation_settle,
)
from agentyc.mcp.network_tools import (
	_add_network_mock,
	_clear_storage,
	_get_frame_html,
	_get_network_conditions,
	_get_storage,
	_inspect_network_entry,
	_list_frames,
	_list_network_mocks,
	_remove_network_mock,
	_replay_request,
	_set_network_conditions,
	_set_storage,
)
from agentyc.mcp.session_lifecycle import (
	_browser_runtime_is_ready,
	_cleanup_expired_sessions,
	_close_all_sessions,
	_close_session,
	_init_browser_session,
	_list_sessions,
	_reset_broken_browser_runtime,
	_shutdown,
	_start_cleanup_task,
	_track_session,
	_update_session_activity,
	_update_session_url,
)
from agentyc.mcp.tool_dispatch import _execute_tool
from agentyc.mcp.tool_feedback import (
	_attach_tool_result_metadata,
	_publish_hud_event,
	_send_log_notification,
	_should_log,
	_tool_output_is_error,
	_tool_phase_message,
	_tool_text_is_error,
)

SERVER_METHODS: dict[str, Any] = {
	'_execute_tool': _execute_tool,
	'_init_browser_session': _init_browser_session,
	'_browser_runtime_is_ready': _browser_runtime_is_ready,
	'_reset_broken_browser_runtime': _reset_broken_browser_runtime,
	'_ensure_extract_runtime': _ensure_extract_runtime,
	'_recover_click_navigation_if_unavailable': _recover_click_navigation_if_unavailable,
	'_resolve_element_index': _resolve_element_index,
	'_cache_state_payload': _cache_state_payload,
	'_mark_browser_state_cache_clean': _mark_browser_state_cache_clean,
	'_mark_browser_state_cache_dirty': _mark_browser_state_cache_dirty,
	'_refresh_selector_map': _refresh_selector_map,
	'_page_contains_visible_text': _page_contains_visible_text,
	'_resolve_live_element': _resolve_live_element,
	'_resolve_upload_available_file_paths': _resolve_upload_available_file_paths,
	'_validate_actionable_element': _validate_actionable_element,
	'_classify_action_error': _classify_action_error,
	'_format_action_error': _format_action_error,
	'_run_tool_action': _run_tool_action,
	'_wait_for_click_navigation_settle': _wait_for_click_navigation_settle,
	'_inject_extraction_metadata': _inject_extraction_metadata,
	'_new_tab_postcondition_satisfied': _new_tab_postcondition_satisfied,
	'_navigate': _navigate,
	'_click': _click,
	'_type_text': _type_text,
	'_upload_file': _upload_file,
	'_get_browser_state': _get_browser_state,
	'_extract_content': _extract_content,
	'_scroll': _scroll,
	'_go_back': _go_back,
	'_go_forward': _go_forward,
	'_refresh': _refresh,
	'_press_key': _press_key,
	'_wait': _wait,
	'_evaluate': _evaluate,
	'_select_option': _select_option,
	'_get_dropdown_options': _get_dropdown_options,
	'_find_elements': _find_elements,
	'_wait_for_element': _wait_for_element,
	'_save_as_pdf': _save_as_pdf,
	'_get_downloads': _get_downloads,
	'_set_viewport': _set_viewport,
	'_search_page': _search_page,
	'_get_html': _get_html,
	'_screenshot': _screenshot,
	'_get_viewport_coords': _get_viewport_coords,
	'_resolve_element_coords': _resolve_element_coords,
	'_hover': _hover,
	'_double_click': _double_click,
	'_drag_to': _drag_to,
	'_scroll_to_text': _scroll_to_text,
	'_save_state': _save_state,
	'_load_state': _load_state,
	'_wait_for_network_idle': _wait_for_network_idle,
	'_right_click': _right_click,
	'_get_cookies': _get_cookies,
	'_set_cookies': _set_cookies,
	'_clear_logs': _clear_logs,
	'_clear_cookies': _clear_cookies,
	'_register_cdp_event_listeners': _register_cdp_event_listeners,
	'_get_console_logs': _get_console_logs,
	'_get_attribute': _get_attribute,
	'_handle_dialog': _handle_dialog,
	'_wait_for_stable_dom': _wait_for_stable_dom,
	'_start_trace': _start_trace,
	'_stop_trace': _stop_trace,
	'_get_network_log': _get_network_log,
	'_wait_for_request': _wait_for_request,
	'_wait_for_response': _wait_for_response,
	'_export_debug_bundle': _export_debug_bundle,
	'_inspect_network_entry': _inspect_network_entry,
	'_tool_phase_message': _tool_phase_message,
	'_should_log': _should_log,
	'_send_log_notification': _send_log_notification,
	'_tool_text_is_error': _tool_text_is_error,
	'_tool_output_is_error': _tool_output_is_error,
	'_attach_tool_result_metadata': _attach_tool_result_metadata,
	'_publish_hud_event': _publish_hud_event,
	'_list_frames': _list_frames,
	'_get_frame_html': _get_frame_html,
	'_get_storage': _get_storage,
	'_set_storage': _set_storage,
	'_clear_storage': _clear_storage,
	'_add_network_mock': _add_network_mock,
	'_remove_network_mock': _remove_network_mock,
	'_list_network_mocks': _list_network_mocks,
	'_set_network_conditions': _set_network_conditions,
	'_get_network_conditions': _get_network_conditions,
	'_replay_request': _replay_request,
	'_get_focused_element': _get_focused_element,
	'_list_tabs': _list_tabs,
	'_new_tab': _new_tab,
	'_switch_tab': _switch_tab,
	'_close_tab': _close_tab,
	'_track_session': _track_session,
	'_update_session_activity': _update_session_activity,
	'_update_session_url': _update_session_url,
	'_set_intent': _set_intent,
	'_list_sessions': _list_sessions,
	'_close_session': _close_session,
	'_close_all_sessions': _close_all_sessions,
	'_cleanup_expired_sessions': _cleanup_expired_sessions,
	'_start_cleanup_task': _start_cleanup_task,
	'_shutdown': _shutdown,
}

__all__ = ['SERVER_METHODS']
