//! Build script for `agentyc-tests`.
//!
//! Reads the (std-only) scenario catalog and emits one `#[ignore] #[test]` per
//! scenario into `$OUT_DIR/generated_real_world.rs`, which `tests/real_world.rs`
//! includes. The catalog is the single source of truth: adding scenarios there
//! automatically grows the generated suite.

#[path = "src/scenario.rs"]
mod scenario;

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/scenario.rs");

    let catalog = scenario::catalog();
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("generated_real_world.rs");

    let mut code = String::with_capacity(catalog.len() * 160);
    code.push_str("// @generated by build.rs from src/scenario.rs — do not edit.\n");
    code.push_str(&format!("// {} real-world scenarios.\n\n", catalog.len()));

    for (i, s) in catalog.iter().enumerate() {
        let slug = sanitize(&s.id);
        code.push_str(&format!(
            "#[test]\n#[ignore = \"real-world battle-test; run with --ignored (needs Chrome)\"]\nfn rw_{i:05}_{slug}() {{ agentyc_tests::run_index({i}); }}\n"
        ));
    }

    fs::write(&dest, code).expect("write generated_real_world.rs");
}

/// Turn a scenario id into a valid, bounded Rust identifier fragment.
fn sanitize(s: &str) -> String {
    let mut out: String = s
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if out.len() > 48 {
        out.truncate(48);
    }
    out
}
